### ISSUE TITLE
Demo code for hand-eye calibration ?

### ISSUE THREAD

**Issue by ldh9299** [ensenso/nxlib-python-interface#11]
Dear author, would you like to show an hand to eye calibration, thanks very much.

**Comment by ldh9299** [comment]
calibrateHandEye.parameters()[ITM_TRANSFORMATIONS] = ??;  so what format should be filled here ,  np.array([[translation_1 + euler_angle_1], [ranslation_2 + euler_angle_2], ...] or list for these parameters, should we use other orientation format like  quat or angle_axis ? @saierd @yguenduez 
Thanks.

**Comment by saierd** [comment]
For an example of a hand-eye calibration, take a look at [the manual](https://www.ensenso.com/manual/3.1/guides/multi-camera-setups-and-calibrations/handeyecalibration.html). You just have to translate this to Python syntax. I guess you already found this, since your line looks similar to the example.

The parameters of the `CalibrateHandEye` command are documented [here](https://www.ensenso.com/manual/3.1/commands/calibratehandeye/parameters.html). In particular, for the `Transformations` parameter, you have to specify a json array of transformations. Each of the transformations should have the json format that is described [here](https://www.ensenso.com/manual/3.1/api/common-tree-elements/typetransformation.html). You will have to convert the rotations to angle-axis representation and fill them in there.

**Comment by ldh9299** [comment]
@saierd 
Dear author, would you like to show me the detail or specify the error in the blew code:

for i in range(20):  
        #move robot and capture pattern here ....
        pose_dict = {'Rotation':{
          "Angle": angle,
          "Axis":[axis[0], axis[1], axis[2]]
                  },
        'Translation': [pose[0]*1000, pose[1]*1000, pose[2]*1000]
        }
        json_array.append(json.dumps(pose_dict))

....

calibration = NxLibCommand(CMD_CALIBRATE_HAND_EYE)
calibration.parameters()[ITM_SETUP] = VAL_FIXED
calibration.parameters()[ITM_TRANSFORMATIONS] = json_array  

but i always get the error with in the last step with type do not match error ?
could you please help me to solve the problem.
Thanks.

**Comment by saierd** [comment]
The `NxLibItem` class only allows to use the assignment operator for primitive types, not for whole subtrees (see the `set_t` method). You have to set the nodes of the transformations individually or use the `set_json` method or the `<<` operator.

In that case the last line should be something like

```python
calibration.parameters()[ITM_TRANSFORMATIONS] << json.dumps(pose_array)
```

In order for this to work, you have to build `json_array` as an array of your `pose_dict`s and not serialize them to strings before.

Note that you can also create the command at the beginning and then fill in the poses during the loop, e.g.

```python
for i in range(20):
   ...
   calibration.parameters()[ITM_TRANSFORMATIONS][i] << json.dumps(pose_dict)
```

**Comment by ldh9299** [comment]
Much thanks for your reply .
yes, set the params in the for loop solve my question.
 however, after i go through the manual, i do not know how to access the calibration result , since i want to check the parameters.
and in the manual , i see we can directly store the calibration result and get the transformed result by set to the target link. however, there are not efficient detail for how to set to the link.

and also  i am not able to set the grid_size :
NxLibItem()[ITM_PARAMETERS][ITM_PATTERN][ITM_GRID_SIZE] = 18.75, since i always meet type error ?
 @saierd

**Comment by saierd** [comment]
After the command `CalibrateHandEye` finished, it will

* Set the calibrated link in the camera's [Link](https://www.ensenso.com/manual/3.1/tree/cameras/120001-%28a-stereo-camera%29/link.html) node. You can save this link to the EEPROM with the `StoreCalibration` command as it is mentioned in the hand-eye calibration guide.
* Output additional information in its [Result node](https://www.ensenso.com/manual/3.1/commands/calibratehandeye/result.html). This is accessible through the NxLib node `calibration.result()` in your code.

---

For the grid spacing, the path mentioned in the manual is actually old (although it should still work). The node is now in [ /Calibration/Pattern/GridSpacing](https://www.ensenso.com/manual/3.1/tree/calibration/pattern/gridspacing.html), so you could try that.

Alternatively, you can also run the `CollectPattern` command with the [DecodeData](https://www.ensenso.com/manual/3.1/commands/collectpattern/parameters/decodedata.html) parameter enabled. This allows it to find out the grid spacing automatically.
