### ISSUE TITLE
How to capture and save depth images?

### ISSUE THREAD

**Issue by ldh9299** [ensenso/nxlib-python-interface#12]

**Comment by ldh9299** [comment]
Dear authors,

I have no idea how to save depth images as .png file rather than just get binary data.

**Comment by saierd** [comment]
You can use the [SaveImage command](https://www.ensenso.com/manual/3.2/commands/saveimage.html) to save binary data from the NxLib in images, e.g.

```py
cmd = NxLibCommand(CMD_SAVE_IMAGE)
cmd.parameters()[ITM_NODE] = NxLibItem()[ITM_CAMERAS]["<serial number>"][ITM_IMAGES][ITM_POINT_MAP].path
cmd.parameters()[ITM_FILENAME] = "point_map.tiff"
cmd.execute()
```

png files are supported as well, but you should note that it might not do what you expect. The depth data consists of floats (point map) or 16 bit numbers (disparity map), both of which might not be accurately represented in a png file. The code above saves to a 3 channel float tiff file, which contains the data correctly, but your image viewer might display it as a transparent image.

**Comment by ldh9299** [comment]
@saierd Thanks for your response. I have tried the code you posted above. I am just wondering why the shape of binary data of point map and disparity map is (1024, 1280, 3) and (1024, 1280, 1) respectively. There are two problems confused me a lot:
1. What are the difference between point map and disparity map? What physical meaning do they represent?
2. In my knowledge, depth image should have 1 channel, so if I want to get a depth image from scene, maybe the disparity map is what I need duo to the same channel number?

**Comment by saierd** [comment]
The disparity map contains the pixel offset between left and right image at each pixel (commonly referred to as "disparity"). The point map contains x,y,z coordinates of the points. See the [manual](https://www.ensenso.com/manual/3.2/tree/cameras/120001-%28a-stereo-camera%29/images/pointmap.html) for more information.

From your description, I guess you want to have an image where each pixel only contains the distance to the camera. This would be the third (z) channel of the point map.

**Comment by ldh9299** [comment]
@saierd Yup, this save my day. Thanks for your help!
