### ISSUE TITLE
Hand-Eye Calibration with 3 DOF

### ISSUE THREAD

**Issue by RayhamGreen** [ensenso/nxlib-python-interface#14]
Good morning, 
first of all, thanks for providing a NxLib-python-interface.
I’m having some trouble getting the hand-eye-calibration to work with 3 DOF.

I started by following this [guide](https://www.ensenso.com/manual/3.2/guides/multi-camera-setups-and-calibrations/handeyecalibration.html). 

```
# Move your robot 
# capture
# collect pattern

if found_pattern:
    # We actually found a pattern. Get the current pose of your robot (from
    # which the pattern was observed) and store it somewhere.
    pose_dict = {'Translation': [var.wx, var.wy, var.wz]
                 }
    # At this point, you need to put your stored robot poses into the command's
    # Transformations parameter.
    calibrate_hand_eye.parameters()[ITM_TRANSFORMATIONS][i].set_json(json.dumps(pose_dict))
```

The poses are stored like it was shown in this [issue](https://github.com/ensenso/nxlib-python-interface/issues/11).

After several cycles I proceed by specifying that we’ve got a moving system with 3 DOF and locked the parameters like it was shown [here](https://www.ensenso.com/manual/3.2/commands/calibratehandeye.html).
```
# We collected enough patterns and can start the calibration.
calibrate_hand_eye.parameters()[ITM_CAMERAS] = str(var.cam_serial)
calibrate_hand_eye.parameters()[ITM_SETUP] = VAL_MOVING  # Or "VAL_FIXED" when your have a fixed setup.
# To calibrate a robot with fewer than 6 DOF you need to lock some parameters
calibrate_hand_eye.parameters()[ITM_FIXED][ITM_PATTERN_POSE][ITM_TRANSLATION][0] = True
calibrate_hand_eye.parameters()[ITM_FIXED][ITM_PATTERN_POSE][ITM_TRANSLATION][1] = True
calibrate_hand_eye.parameters()[ITM_FIXED][ITM_PATTERN_POSE][ITM_TRANSLATION][2] = True

calibrate_hand_eye.execute()


# Store the new calibration to the camera's EEPROM.
store_calibration = NxLibCommand(CMD_STORE_CALIBRATION)
store_calibration.parameters()[ITM_CAMERAS] = str(var.cam_serial)
store_calibration.parameters()[ITM_LINK] = True
store_calibration.execute()
```

Executing, storing and a look at the results.
```
results = NxLibItem()[ITM_CAMERAS][ITM_BY_SERIAL_NO][str(var.cam_serial)][ITM_LINK][ITM_TRANSLATION].as_json()
print("The Translation is {}".format(results))
```

I actually get results like:
The Translation is [-15, 8.8, 4.8]
With this complete I set the second [link](https://www.ensenso.com/manual/3.1/tree/links.html) by providing the position of the robot, when I take the next picture.
```
# Compute the disparity map

# Report the current pose of the robot hand (work coordinates) to the NxLib by setting the hand link.
NxLibItem()[ITM_LINKS][VAL_HAND] << json.dumps({'Translation': [var.wx, var.wy, var.wz]})

# Compute the point map from the disparity map
```

Afterwards I search for the highest and lowest z-Value and return its position.
```
# retrieving resolution of camera picture
x_length = var.points.shape[0]
y_length = var.points.shape[1]

# replacing all nan-z-values with zeros
for y in range(y_length):
    for x in range(x_length):
        if math.isnan(var.points[x, y, 2]):
            var.points[x, y, 2] = 0

# find maximum z-value
max_value = np.max(var.points[:, :, 2])
print('Maximum value of the array is', max_value)

# find minimum z-value
min_value = np.min(var.points[:, :, 2])
print('Minimum value of the array is', min_value)

# find the location of max z-value
max_pos = np.where(var.points == max_value)
print("\nPosition of max value in the list is:", max_pos[0], max_pos[1])

# find the location of max z-value
min_pos = np.where(var.points == min_value)
print("\nPosition of min value in the list is:", min_pos[0], min_pos[1])

print(var.points[max_pos[0], max_pos[1]])

print(var.points[min_pos[0], min_pos[1]])
```

To test the system, I placed an object with a known hight at a known location. Then I moved the robot’s hand, so the camera is able to capture an image of the object and try to find its location in workspace coordinates.
So, the objects highest point is located at [200, 200, 50]
While capturing the robot’s hand is at [300, 300, 90]
But the return is:
Maximum value of the array is 0.0
Minimum value of the array is -506.3263
Position of max value in the array is: “multiple positions”
Position of min value in the array is: [65] [90]
[-118.492485 -488.93295  -506.3263 ]
So, I expect the result to be [200, 200, 50], but I get [-118.492485 -488.93295  -506.3263 ].
An I guess the hand-eye-calibration is the problem, because I would expect the translation in the link between Camera and Hand to be something like [-170, -90, 310] and not [-15, 8.8, 4.8].

Could you please help me find my mistake?
Thanks a lot in advance.

**Comment by saierd** [comment]
Hand-eye calibration is quite a tricky topic, especially with reduced DOF. You already found the [documentation here](https://www.ensenso.com/manual/3.2/commands/calibratehandeye.html), but I guess I have to clarify some points.

With a 3DOF robot, it is impossible to calibrate the translation between robot and camera. We can only calibrate the rotation. This is because we cannot observe any rotations and therefore a translation of the calibration pattern is indistinguishable from a translation of the camera/robot.

In this case you have to compute the translation manually by some other means, e.g. by observing a known point of the robot in the 3D data and adjusting the translation so that the point ends up at the desired position. You can either just modify the link in the camera node and save it, or you can specify the translation in the [initial guess](https://www.ensenso.com/manual/3.2/commands/calibratehandeye/parameters/patternpose.html) for the calibration. When the translation is fixed, the calibration procedure will not modify it.

In your example you did not specify any initial guesses. They will be computed automatically, with a translation that is essentially random.

**Comment by RayhamGreen** [comment]
Thank you for the very quick clarification and explanation. I'll try to adapt my code with the information provided. If further complications arise, I'll get back to you.
