### ISSUE TITLE
Why ITM_VIEW_POSE in my CMD_RENDER_VIEW doesn't work

### ISSUE THREAD

**Issue by aaaa47080** [ensenso/nxlib-python-interface#15]
[](url)Excuse me, I want to ask.

I try to adjust the ITM_VIEW_POSE parameter in CMD_RENDER_VIEW to achieve the top view state I want to save, but no matter how I adjust it, the top view state does not change, the following is my code:

```
from ensenso_nxlib import NxLibCommand, NxLibItem
from ensenso_nxlib.constants import *
import ensenso_nxlib


stereo_serial = "193244"
mono_serial = "4103989237"

ensenso_nxlib.api.initialize()

cmd = NxLibCommand(CMD_OPEN)
cmd.parameters()[ITM_CAMERAS][0] = stereo_serial
cmd.parameters()[ITM_CAMERAS][1] = mono_serial
cmd.execute()


stero_cam = NxLibItem()[ITM_CAMERAS][stereo_serial]
param = json.dumps(json.load(open('parameter.json', "r")))
stero_cam << param
print('Load the stereo Camera parameter file....')

mono_cam = NxLibItem()[ITM_CAMERAS][mono_serial]
param = json.dumps(json.load(open('parameter.json', "r")))
mono_cam << param
print('Load the  mono  Camera parameter file....')

parameters_tree_json =  json.dumps(json.load(open('123.json', "r")))
NxLibCommand(CMD_CAPTURE).execute()
NxLibCommand(CMD_COMPUTE_DISPARITY_MAP).execute()

view_sence = NxLibCommand(CMD_RENDER_VIEW)
view_sence.parameters()[ITM_CAMERA] = mono_serial
view_sence.parameters()[ITM_VIEW_POSE] = parameters_tree_json
view_sence.execute()

view_sence = NxLibCommand(CMD_SAVE_IMAGE)
view_sence.parameters()[ITM_NODE] = NxLibItem()[ITM_IMAGES][ITM_RENDER_VIEW]
view_sence.parameters()[ITM_FILENAME] = "test4.jpg"
view_sence.execute()
```

123.txt is the json file that I used ITM_VIEW_POSE to change the position, but whether it was used or not ITM_VIEW_POSE did not affect the last image stored in the overhead view. The results will also be attached below

![test3](https://user-images.githubusercontent.com/102430570/160251592-015be16a-42aa-4b47-9fd8-32e3d391465f.jpg)
![test4](https://user-images.githubusercontent.com/102430570/160251593-b77a8d1c-8784-413d-830c-2f224b81245d.jpg)
[123.txt](https://github.com/ensenso/nxlib-python-interface/files/8356053/123.txt)

**Comment by saierd** [comment]
The problem is this line:

```py
view_sence.parameters()[ITM_VIEW_POSE] = parameters_tree_json
```

This makes the parameter a string node with the json as the string content. This then gets overwritten by the default pose again. To apply the json string to the NxLib tree you have to use the `set_json` method or the `<<` operator as you correctly did a few lines above.

**Comment by aaaa47080** [comment]
Thank you very much sir, I made it. But I'm sorry, please allow me to ask another simple question. If I want to modify the parameters of POINTCLOUD in ITM_RENDER, like the POINTSIZE part, what JSON file format should I use, and because he has no corresponding ITM options(like ITM_VIEW_POSE), So this has me a bit at a loss, could you please provide an example syntax, or an archive for reference

**Comment by saierd** [comment]
Yes, the constants are pretty old at the moment and `PointSize` is not in there yet. This will change soon when we publish a new version of the SDK.

For now you can use strings like this:

```py
view_sence.parameters()["PointCloud"]["PointSize"] = 1
```

**Comment by aaaa47080** [comment]
Ok sir, thank you very much, if you have any questions I will come up and ask again, have a nice day

**Comment by saierd** [comment]
:+1: Feel free to reopen if you have further questions.
