### ISSUE TITLE
Can I open camera in one terminal and capture pointclouds in another terminal?

### ISSUE THREAD

**Issue by F2Wang** [ensenso/nxlib-python-interface#2]
Hi, I wonder if there is a way to open a camera and keep it running, so that in another script I can call the camera to capture a pointcloud at anytime? It seems like initilizing the api and open a camera takes a long time.

Thanks!

**Comment by saierd** [comment]
Yes, this is possible. You can open a TCP port in a long running process and then use the NxLibRemote to connect to it from another process.

Server:

```python
import signal
import sys

import ensenso_nxlib

def handle_sigint():
    sys.exit(0)

ensenso_nxlib.api.open_tcp_port(24000)

# You can open your camera here or remotely from the other process.

signal.signal(signal.SIGINT, handle_sigint)
signal.pause()
```

Client:

```python
import ensenso_nxlib

ensenso_nxlib.api.load_remote_lib()
ensenso_nxlib.api.connect("localhost", 24000)

# Use the NxLib API normally from here on. Everything will be forwarded to the server process.
```

**Comment by F2Wang** [comment]
Really appreciate the prompt reply, the method works like a charm!
