### ISSUE TITLE
Example Code of Accessing the Monocular Camera Data

### ISSUE THREAD

**Issue by yongxf** [ensenso/nxlib-python-interface#4]
Thanks for your neat code!
It seems there is no related code for monocular camera. I understand the examples/nx_list_cams.py can read the monocular camera serial No, and there is constant related to monocular (ITM_MONOCULAR). However, I am curious whether it's possible to access the monocular image. 
something like this: camera[ITM_IMAGES][ITM_RAW][ITM_LEFT].get_binary_data()

Thanks in advance!

**Comment by saierd** [comment]
This Python package is only a wrapper for the C API of the NxLib. You should look at the [manual](https://www.ensenso.com/manual/2.3/) for information about the tree structure.

In particular, the structure of a mono camera tree is documented [here](https://www.ensenso.com/manual/2.3/index.html?_cameras_$monoserial.htm). It is usually very similar to the tree of a stereo camera, but some features are missing and there is of course only one image. The raw image is in [this node](https://www.ensenso.com/manual/2.3/index.html?_cameras_$monoserial_images_raw.htm), so you can retrieve it with

```python
camera[ITM_IMAGES][ITM_RAW].get_binary_data()
```

**Comment by yongxf** [comment]
Thanks a lot, the structure works as expected. I should have checked the manual first. 
Appreciate for your help!
