### ISSUE TITLE
How to set the parameters json to the nxlib?

### ISSUE THREAD

**Issue by namuhevil** [ensenso/nxlib-python-interface#5]
Because I want to filter by the explosure rate.
Can you tell me how to do that? How to set it?

**Comment by saierd** [comment]
If you want to set a single parameter, you can simply write to the corresponding node, e.g.

```python
camera[ITM_PARAMETERS][ITM_CAPTURE][ITM_EXPOSURE] = 5
```

If you want to apply a complete json tree, you can use the `set_json` function or the `<<` operator:

```python
parameters_tree_json = "..." # Load json somehow.
camera[ITM_PARAMETERS] << parameters_tree_json
```

Note that NxView exports not just the parameters tree, but the whole camera tree including the calibration and the link. If you want to load all of them, you can write it directory to the camera node. If you want to load only parts of it, you need to parse the json, extract the relevant nodes and write them to the corresponding NxLib node.

For more information, see the [manual](https://www.ensenso.com/manual/2.3/index.html?howto_parameterfiles.htm), which contains examples using the C++ API.

**Comment by namuhevil** [comment]
for set_json methods. is like api.set_json("path/", files.json).
like this?

**Comment by saierd** [comment]
Yes, `api.set_json` corresponds to the C NxLib function [`nxLibSetJson`](https://www.ensenso.com/manual/2.3/index.html?nxlibsetjson.htm). The path must start with a `/`.

There is also a `set_json` method on the `NxLibItem` object (corresponding to [this](https://www.ensenso.com/manual/2.3/index.html?setjson.htm) C++ function), which makes it easier to build the path, e.g.

```python
camera = NxLibItem()[ITM_CAMERAS]["123456"]
camera[ITM_PARAMETERS].set_json("{...}")
```

Note that both of these functions have an optional parameter `only_writeable_nodes`. If you want to overwrite things in the camera tree, you want to set this to true, since there are read only nodes in the parameter trees. The `<<` operator is equivalent to calling `set_json` with `only_writeable_nodes` enabled.

**Comment by namuhevil** [comment]
```python
from ensenso_nxlib import NxLibCommand, NxLibException, NxLibItem
from ensenso_nxlib.constants import *
import ensenso_nxlib.api as api

import argparse
import open3d as o3d
import numpy


def _ensenso_to_open3d(ensenso_pc):
    point_cloud = o3d.geometry.PointCloud()

    # Reshape from (m x n x 3) to ( (m*n) x 3)
    vector_3d_vector = ensenso_pc.reshape(
        (ensenso_pc.shape[0] * ensenso_pc.shape[1]), ensenso_pc.shape[2])

    # Filter nans: if a row has nan's in it, delete it
    vector_3d_vector = vector_3d_vector[~numpy.isnan(
        vector_3d_vector).any(axis=1)]
    point_cloud.points = o3d.utility.Vector3dVector(vector_3d_vector)
    return point_cloud


def main(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--serial", type=str, required=True,
                        help="The serial of the stereo camera, you want to open")
    args = parser.parse_args(args)

    camera_serial = args.serial

    try:
        # Waits for the cameras to be initialized
        api.initialize()
        api.set_json("", "parameters.json")
        # parameters = "parameters.json"

        # Opens the camera with the serial stored in camera_serial variable
        cmd = NxLibCommand(CMD_OPEN)
        cmd.parameters()[ITM_CAMERAS] = camera_serial
        
        # cmd[ITM_PARAMETERS] << "parameters.json"
        # cmd[ITM_PARAMETERS][ITM_CAPTURE][ITM_EXPOSURE] = "4"
        # cmd.parameters()[ITM_PARAMETERS] = parameters
        # cmd.execute()

        # Captures with the previous openend camera
        capture = NxLibCommand(CMD_CAPTURE)
        capture.parameters()[ITM_CAMERAS] = camera_serial
        capture.execute()

        # Rectify the the captures raw images
        rectification = NxLibCommand(CMD_RECTIFY_IMAGES)
        rectification.execute()

        # Compute the disparity map
        disparity_map = NxLibCommand(CMD_COMPUTE_DISPARITY_MAP)
        disparity_map.execute()

        # Compute the point map from the disparitu map
        point_map = NxLibCommand(CMD_COMPUTE_POINT_MAP)
        point_map.execute()
        points = NxLibItem()[ITM_CAMERAS][camera_serial][ITM_IMAGES][ITM_POINT_MAP].get_binary_data()

        # Watch the captured point cloud with open3d-python
        point_cloud = _ensenso_to_open3d(points)
        o3d.visualization.draw_geometries([point_cloud])

        # Closes all open cameras
        NxLibCommand(CMD_CLOSE).execute()

    except NxLibException as e:
        print("An NxLibException occured: Error Text: {}".format(e.get_error_text()))
    except:
        print("Something bad happenend, that has been out of our control.")


if __name__ == "__main__":
    import sys
    main(sys.argv[1:])
```

api.set_json("", "parameters.json")
is that correct what I wrote? But it happend errors. How can I write it?

**Comment by saierd** [comment]
No. The parameter for the function is a json string, not a filename. You need to load the json data from the file yourself. Additionally, you need to set_json on the correct tree node.

As an example, you can insert the following code after the open command (where your commented out code is).

```python
camera_node = NxLibItem()[ITM_CAMERAS][camera_serial]
camera_node[ITM_PARAMETERS] << '{"Capture": {"Exposure": 5}}'
```

**Comment by namuhevil** [comment]
I already try the code you give me but it is not work.

        # Opens the camera with the serial stored in camera_serial variable
        cmd = NxLibCommand(CMD_OPEN)
        cmd.parameters()[ITM_CAMERAS] = camera_serial
        cmd[ITM_PARAMETERS] << '{"Capture": {"Exposure": 5}}'
        cmd.execute()

Can you give my python code to test? please.

**Comment by saierd** [comment]
That's not what I meant. You have to insert the code *after* the open command was executed and the code should not be applied to the open command's parameter, but modify the NxLib tree after the command was executed.

You should also read the basic examples about how the NxLib works [here](https://www.ensenso.com/manual/2.3/index.html?howtos_basiccameraoperations.htm). The examples are in C++, but the Python API provides exactly the same functions except for the different naming conventions.

**Comment by saierd** [comment]
I am closing this, feel free to reopen it if you still have problems.
