### ISSUE TITLE
part of the point cloud is missing due to improper distance setting

### ISSUE THREAD

**Issue by yongxf** [ensenso/nxlib-python-interface#6]
Hi there, 
thanks for the python tool. I have a scene that captured by nxView (first image). I set the workspace and far/near distance in the nxView. 
However, when I captured the point cloud with python interface, it seems the bin is totally missing (below image). I think the near/far distance setting is not passed to python successfully. When I set them in python by: 

`NxLibItem()[ITM_CAMERAS][camera_serial][ITM_PARAMETERS][ITM_DISPARITY_MAP][ITM_MEASUREMENT_VOLUME][ITM_NEAR][ITM_LEFT_BOTTOM][2].set_binary_data(np.array([[[350]]]).astype(np.float32))`

It returns NxLibItemTypeNotCompatible error. I also tried np.int32, np.float64, same error appears. It even returns the same error when I use get_binary_data() (gives some value though). 
My camera is about 0.7 m to the bin. 

I am not sure whether the ITM_MEASUREMENT_VOLUME->ITM_NEAR is the correct place to set the far/near distance. Can you shed some lights on this? Thanks a lot!

![Screenshot from 2020-08-21 14-17-41](https://user-images.githubusercontent.com/18318195/90936330-d75ef180-e3b9-11ea-9589-f2490b95a6bd.png)
![Screenshot from 2020-08-21 14-16-22](https://user-images.githubusercontent.com/18318195/90936365-e80f6780-e3b9-11ea-9c9c-72ce4e1ff4c9.png)

**Comment by saierd** [comment]
The node is the correct place to set up the depth range. It is not a binary node, though, it is a number. The [manual page](https://www.ensenso.com/manual/2.3/index.html?_cameras_$stereoserial_parameters_disparitymap_measurementvolume_far_leftbottom.htm) for this node (and any other node) documents the JSON type that the node can have.

Example:

```python
NxLibItem()[ITM_CAMERAS][camera_serial][ITM_PARAMETERS][ITM_DISPARITY_MAP][ITM_MEASUREMENT_VOLUME][ITM_NEAR][ITM_LEFT_BOTTOM][2] = 350
```

For completeness: It is also possible to [set the disparities directly](https://www.ensenso.com/manual/2.3/index.html?_cameras_$stereoserial_parameters_disparitymap_stereomatching_minimumdisparity.htm) or [load the settings from a JSON file that you can export from NxView](https://www.ensenso.com/manual/2.3/index.html?howto_parameterfiles.htm).

**Comment by yongxf** [comment]
Thanks @saierd for the prompt help. 
The code 
`NxLibItem()[ITM_CAMERAS][camera_serial][ITM_PARAMETERS][ITM_DISPARITY_MAP][ITM_MEASUREMENT_VOLUME][ITM_NEAR][ITM_LEFT_BOTTOM][2] = 350
`
works fine for my camera. I will try to use JSON file later.

**Comment by aaaa47080** [comment]
I'm sorry sir, I don't know where I made a mistake, can you please help me

```
while path_num != 3:
    stereo_serial = "193244"
    mono_serial = "4103989237"

    ensenso_nxlib.api.initialize()

    cmd = NxLibCommand(CMD_OPEN)
    cmd.parameters()[ITM_CAMERAS][0] = stereo_serial
    cmd.parameters()[ITM_CAMERAS][1] = mono_serial
    cmd.execute()

    stero_cam = NxLibItem()[ITM_CAMERAS][stereo_serial]
    # param = json.dumps(json.load(open('stero_serial_2.json', "r")))
    # stero_cam << param
    #print('Load the stereo Camera parameter file....')

    mono_cam = NxLibItem()[ITM_CAMERAS][mono_serial]
    # param = json.dumps(json.load(open('mono_serial_2.json', "r")))
    # mono_cam << param
    #print('Load the  mono  Camera parameter file....')
    NxLibItem()[ITM_CAMERAS][str(mono_serial)][ITM_PARAMETERS][ITM_CAPTURE][ITM_TRIGGER_MODE] = VAL_FALLING_EDGE
    cputer = NxLibCommand(CMD_CAPTURE)
    # NxLibItem()[ITM_CAMERAS][str(mono_serial)][ITM_PARAMETERS][ITM_CAPTURE][ITM_TRIGGER_MODE] = VAL_FALLING_EDGE
    cputer.execute()
    NxLibCommand(CMD_COMPUTE_DISPARITY_MAP).execute()
    NxLibCommand(CMD_COMPUTE_POINT_MAP).execute()
    cmd = NxLibCommand(CMD_RENDER_POINT_MAP)
```
This will display an error like "Message": "Received new image from camera."
