### ISSUE TITLE
How to change scan quality on x36-5CP with Python Interface

### ISSUE THREAD

**Issue by sieuwe1** [ensenso/nxlib-python-interface#7]
Hi

I am using a X36-5CP to scan some products. For this I am using the Python interface to automate the process. I am using the nx_watch_point_cloud.py as an example. I want to scan each product in different qualities. How can I change the quality of the 3D scan?

I am using this code but it is not working. I use NX view to set quality low and then save the settings .json file. I called this file LOW quality. And then set the quality to high in NX view and saved the .json file as HIGH quality. But with the code below there is no difference in scan quality between the two .json settings files. 

def scan(camera_serial):

    # Waits for the cameras to be initialized
    api.initialize()

    # Opens the camera with the serial stored in camera_serial variable
    cmd = NxLibCommand(CMD_OPEN)
    cmd.parameters()[ITM_CAMERAS] = camera_serial
    cmd.execute()

    #sets param
    param = json.dumps(json.load(open("C:\Inspection\data-maker\LOW_detail.json", "r")))
    #param = json.dumps(json.load(open("C:\Inspection\data-maker\HIGH_detail.json", "r")))
    camera_node = NxLibItem()[ITM_CAMERAS][camera_serial]
    camera_node[ITM_PARAMETERS] << param

    # Captures with the previous openend camera
    capture = NxLibCommand(CMD_CAPTURE)
    capture.parameters()[ITM_CAMERAS] = camera_serial
    capture.execute()

    # Rectify the the captures raw images
    rectification = NxLibCommand(CMD_RECTIFY_IMAGES)
    rectification.execute()

    # Compute the disparity map
    disparity_map = NxLibCommand(CMD_COMPUTE_DISPARITY_MAP)
    disparity_map.execute()

    # Compute the point map from the disparitu map
    point_map = NxLibCommand(CMD_COMPUTE_POINT_MAP)
    point_map.execute()
    points = NxLibItem()[ITM_CAMERAS][camera_serial][ITM_IMAGES][ITM_POINT_MAP].get_binary_data()

    return ensenso_to_open3d(points)

**Comment by yguenduez** [comment]
Hello Sieuwe,

I guess you are saving the json file directly and do not modify it. In that case the json file includes not only the camera parameters, but also the camera calibration and [other things](https://www.ensenso.com/manual/3.0/tree/cameras/stereoserial.html) - so there is an extra hierarchy in between. Basically you did not set anything in this case, because the matching keys were not found.

If you only want to overwrite the parameters, you will have to extract the parameter (sub) json out of the json you saved from NxView, like so (not tested):
```python
camera_config_dict = json.load(open("C:\Inspection\data-maker\LOW_detail.json", "r"))
camera_parameters = camera_config_dict[ITM_PARAMETERS]
camera_node = NxLibItem()[ITM_CAMERAS][camera_serial]
camera_node[ITM_PARAMETERS] << json_dumps(camera_parameters)
```

Or you could simpy overwrite the whole camera_node:
```python
param = json.dumps(json.load(open("C:\Inspection\data-maker\LOW_detail.json", "r")))
camera_node = NxLibItem()[ITM_CAMERAS][camera_serial]
camera_node << param
```
Only writeable Nodes will get overwritten of course. But the latter case will also overwrite your calibration.

**Comment by yguenduez** [comment]
I'll close the issue for now. If you have any other questions regarding this issue feel free to reopen it.

**Comment by sieuwe1** [comment]
Hi Yasin,

Sorry for not replying. Your fix has indeed worked and I have been using it to scan in the products in different qualities.

Thanks for your help,

Sieuwe

________________________________
Van: Yasin Guenduez <notifications@github.com>
Verzonden: dinsdag 5 januari 2021 13:45
Aan: ensenso/nxlib-python-interface <nxlib-python-interface@noreply.github.com>
CC: sieuwe elferink <sieuwe_crossen@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [ensenso/nxlib-python-interface] How to change scan quality on x36-5CP with Python Interface (#7)


I'll close the issue for now. If you have any other questions regarding this issue feel free to reopen it.
