### ISSUE TITLE
Mapping from Images to pointcloud

### ISSUE THREAD

**Issue by F2Wang** [ensenso/nxlib-python-interface#9]
Thank you for the great work and for providing the examples to acquire depth image pairs and pointcloud, I am trying to map from one depth image to pointcloud (e.g., get 3D point positions for each pixels on the depth image), and I wonder if there is anyway to do so.

Thanks,

**Comment by saierd** [comment]
The point map already contains the points you want. See e.g. [nx_simple.py](https://github.com/ensenso/nxlib-python-interface/blob/master/examples/nx_simple.py) for how to compute the point map. In the `compute_average_z` function, this example only extracts the z component of the points, but it contains x and y as well in `point[0]` and `point[1]` respectively.

**Comment by F2Wang** [comment]
Thank you for your prompt reply! I think I didn't phrase my questions very clear...I am able to obtain the image pairs and pointclouds, but I want to find out, for example, the corresponding x,y,z measurement for the (300,400) pixel on the left image. Is it possible to do with this repository?

**Comment by saierd** [comment]
Yes, that is possible. The entries of the point map are aligned with the pixels of the camera's [left rectified image](https://www.ensenso.com/manual/3.0/tree/cameras/120001-%28a-stereo-camera%29/images/rectified/left.html). You can simply use the same pixel positions in both of them.

Note that this is only true for the left rectified image, not for the left raw image and not for the right images, so you have to make sure that you extract the correct image from the API.

**Comment by F2Wang** [comment]
Thank you for the very useful information!
